/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as ComponentsNameRouteImport } from './routes/components.$name'
import { Route as BlocksNameRouteImport } from './routes/blocks.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNameRoute = ComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksNameRoute = BlocksNameRouteImport.update({
  id: '/blocks/$name',
  path: '/blocks/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/components/$name': typeof ComponentsNameRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/components/$name': typeof ComponentsNameRoute
  '/blocks': typeof BlocksIndexRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/components/$name': typeof ComponentsNameRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks/$name'
    | '/components/$name'
    | '/blocks/'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blocks/$name' | '/components/$name' | '/blocks' | '/components'
  id:
    | '__root__'
    | '/'
    | '/blocks/$name'
    | '/components/$name'
    | '/blocks/'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksNameRoute: typeof BlocksNameRoute
  ComponentsNameRoute: typeof ComponentsNameRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$name': {
      id: '/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof ComponentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$name': {
      id: '/blocks/$name'
      path: '/blocks/$name'
      fullPath: '/blocks/$name'
      preLoaderRoute: typeof BlocksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksNameRoute: BlocksNameRoute,
  ComponentsNameRoute: ComponentsNameRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
